#!/bin/bash -e
if [[ ! -f "/home/spark-7dd64450-8d7a-4513-bd1b-68/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-7dd64450-8d7a-4513-bd1b-68/tmp/uv/uv_0.6.10_linux_amd64" "$@"
